# Generated by Django 3.1.2 on 2020-12-12 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Savedfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file')),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jokes.login')),
            ],
        ),
    ]
