# Generated by Django 3.1.2 on 2020-12-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0002_savedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedfile',
            name='Username',
            field=models.CharField(max_length=30),
        ),
    ]
